services:
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos
    env_file:
      - .env
    restart: always
    ports:
      - "8848:8848"       # 控制台端口
      - "9848:9848"       # gRPC端口（Nacos 2.x 必需）
    volumes:
      - nacos_logs:/home/nacos/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/v1/ns/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  nacos_logs: